services:
  upgist:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ~/.ssh:/root/.ssh:ro  # Map SSH keys read-only
    environment:
      - GIST_URL=${GIST_URL:?GIST_URL is required}
      - GITHUB_USERNAME=${GITHUB_USERNAME:?GITHUB_USERNAME is required}
      - GIT_USER=${GIT_USER:-UpGist}
      - GIT_EMAIL=${GIT_EMAIL:-upgist@local}
      - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE:-Add files via UpGist}
      - UPGIST_LOGGING=${UPGIST_LOGGING:-}
    init: true
