services:
  upgist:
    image: ghcr.io/zachatrocity/upgist:main
    ports:
      - "3000:3000"
    volumes:
      - ~/.ssh:/root/.ssh:ro  # Map SSH keys read-only
      - $SSH_AUTH_SOCK:/ssh-agent # Forward SSH agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - GIST_URL=${GIST_URL:?GIST_URL is required}
      - GITHUB_USERNAME=${GITHUB_USERNAME:?GITHUB_USERNAME is required}
      - GIT_USER=${GIT_USER:-UpGist} #optional
      - GIT_EMAIL=${GIT_EMAIL:-upgist@local} #optional
      - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE:-Add files via UpGist} #optional
      - UPGIST_LOGGING=${UPGIST_LOGGING:-} #optional
    init: true
