services:
  upgist:
    # build: . # for development
    image: ghcr.io/zachatrocity/upgist:main
    ports:
      - "3000:3000"
    volumes:
      # Mount SSH keys for container's internal SSH agent
      # Note: gist.github.com needs to be in known_hosts
      - ~/.ssh:/root/.ssh:ro
    environment:
      - GIST_URL=${GIST_URL:?GIST_URL is required}
      - GITHUB_USERNAME=${GITHUB_USERNAME:?GITHUB_USERNAME is required}
      - GIT_USER=${GIT_USER:-UpGist} # optional
      - GIT_EMAIL=${GIT_EMAIL:-upgist@local} # optional
      - GIT_COMMIT_MESSAGE=${GIT_COMMIT_MESSAGE:-Add files via UpGist} # optional
      - UPGIST_LOGGING=${UPGIST_LOGGING:-} # optional
    init: true
